#!/usr/local/bin/fish

set formula $argv[-2]
set version $argv[-1]

set -l REPO (brew --repository)/Library/Taps/homebrew/homebrew-cask/
set -l HASH (git -C $REPO log --format=%H\ %s --grep=$version | grep $formula | awk '{ print $1 }' | head -n 1)
set -l URL (brew cask info $formula 2>&1 | grep '^From:' | cut -d ' ' -f 2 | sed 's/github/raw.githubusercontent/g' | sed "s/blob\/master/$HASH/g")

brew cask install $URL
