#!/usr/bin/env bash

die() {
  echo "error: $1"
  echo "Look pal, something went awfully wrong and I'm gonna have to cancel this commit."
  exit 1
}

relative_root=$(git rev-parse --show-cdup)
staged_files=$(git diff --cached --name-only)
for path in $staged_files; do
  file=${relative_root:-.}$path

  case $(file -i $file) in
      text/x-shellscript) 
          # h/t https://stackoverflow.com/a/171932/8738498
          bash -n $file || die "bash threw an error while validating $file"
      ;;
  esac

  case $(basename file) in
    *.plist)
      case $(uname) in
        Darwin) plutil $file || die "plutil threw an error whlile validating $file";;
        *) 
          # fixme: Use an XML validator? 
          die "tbh i have no idea how to validate XML on $(uname)."
        ;;
      esac
    ;;

    *.service)
      case $(uname) in
        Linux) systemd-analyze verify $file ;;
        *) die "I'm not going to validate $file because this system isn't Linux-based."
      esac
    ;;
  esac
done

echo "Steady as she goes cap'n."
